# Generated by Django 5.1.2 on 2024-11-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='couverture_link',
            field=models.CharField(max_length=255),
        ),
    ]
