# Generated by Django 5.1.2 on 2024-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0002_alter_livre_couverture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='couverture_link',
        ),
        migrations.AddField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers/'),
        ),
    ]
