# Generated by Django 5.1.2 on 2024-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0003_remove_livre_couverture_link_livre_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
