# Generated by Django 5.1.2 on 2024-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0004_clients_email_clients_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='nb_livre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livre',
            name='statu',
            field=models.CharField(default='disponible', max_length=255),
        ),
    ]
