# Generated by Django 5.1.2 on 2025-01-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0005_clients_nb_livre_livre_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='statu',
            new_name='status',
        ),
    ]
