# Generated by Django 5.1.2 on 2025-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0005_clients_nb_livre_livre_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='role',
            field=models.CharField(default='user', max_length=80),
        ),
    ]
