# Generated by Django 5.1.2 on 2025-01-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0006_clients_role'),
        ('gestionDeBibiliotheque', '0006_rename_statu_livre_status'),
    ]

    operations = [
    ]
