# Generated by Django 5.1.2 on 2025-01-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0007_merge_20250116_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='nbr_point',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='livre',
            name='nbr_point_liver',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
