# Generated by Django 5.1.2 on 2025-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0008_coinspromo_livre_num_borrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinspromo',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coinspromo',
            name='bonus_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinspromo',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinspromo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinspromo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coinspromo',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
