# Generated by Django 5.1.2 on 2025-01-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0008_clients_nbr_point_livre_nbr_point_liver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('bonus_coins', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDeBibiliotheque.clients')),
                ('coins_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionDeBibiliotheque.coinspromo')),
            ],
        ),
    ]
