# Generated by Django 5.1.2 on 2025-01-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0009_coinspromo_price_coinspromo_bonus_coins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinspromo',
            old_name='Price',
            new_name='price',
        ),
    ]
