# Generated by Django 5.1.2 on 2025-01-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0009_coinspromo_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='status',
            field=models.CharField(default='indisponible', max_length=255),
        ),
    ]
