# Generated by Django 5.1.2 on 2025-01-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0010_emprunt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
