# Generated by Django 5.1.2 on 2025-01-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDeBibiliotheque', '0011_livre_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
